#!/bin/bash

source "$OPENSHIFT_REPO_DIR/.openshift/custom-nodejs-version/build"

# For datstack, copy configs, run unit tests and grunt. Set the home directory
# before executing the build since things like bower will write into HOME,
# which we cant do on openshift.
(
   cd ${OPENSHIFT_REPO_DIR};
   cp .openshift/files/database.json .;
   npm run test;
   HOME=$HOME/app-root/data npm run build;
)
